services:
  - type: web
    name: resume-screener-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
